### ISSUE TITLE
Fires on page load

### ISSUE THREAD

**Issue by uvarovdev** [hryvinskyi/magento2-invisible-captcha#7]
Hi! Captcha fires on page load, not even on form submit. Any ideas?
Magento 2.3.4 on any page.

**Comment by hryvinskyi** [comment]
@McAlex220 

captcha is load after clicking on any element on page or submit a form. also be load if page has input autofocus
please add more information is needed for more detailed help

**Comment by uvarovdev** [comment]
Look at e-mail..

**Comment by hryvinskyi** [comment]
answered you

**Comment by uvarovdev** [comment]
I don't see any other answers except [this one](https://github.com/hryvinskyi/magento2-invisible-captcha/issues/7#issuecomment-710587820). Did you look at the site i sent you by email?
The problem is not in captcha load. When page loads - captcha fires verification. 
Maybe i miss something, but captcha should fire verification only after form submit, not on page load.
[http://joxi.ru/12MkdpjU03XW8r](http://joxi.ru/12MkdpjU03XW8r)

**Comment by hryvinskyi** [comment]
@McAlex220 i cant reproduce this issue
