### ISSUE TITLE
Magento 2.4.6 compatibility 

### ISSUE THREAD

**Issue by fvlasie** [hryvinskyi/magento2-invisible-captcha#8]
Hello,

Is this module compatible with Magento 2.4.6?

**Comment by hryvinskyi** [comment]
Hi @fvlasie 
This module has not been tested on Magento 2.4.6

**Comment by fvlasie** [comment]
OK I will test it and let you know!

**Comment by fvlasie** [comment]
I can confirm the module works with Magento 2.4.6 !
